"""Pure domain vocabulary for the agent engine.

The innermost layer. Depends on nothing -- not the standard library's I/O, not
third-party packages, and certainly not adapters. Everything here is data.
"""

from engine.domain.agents import AgentInstance, AgentProfile, AgentRun, AgentRunStatus
from engine.domain.approvals import (
    ApprovalDecision,
    ApprovalDecisionSource,
    ApprovalKind,
    ApprovalRecord,
    ApprovalStatus,
    SessionGrant,
)
from engine.domain.chat import Conversation, Message, Role, ToolCall
from engine.domain.commands import (
    Command,
    Notify,
    PersistRun,
    ProvisionWorkspace,
    PublishChanges,
    ScheduleTimer,
    StartAgentRun,
)
from engine.domain.events import Event, RunFailed, StepCompleted
from engine.domain.findings import (
    REVIEW_BRANCH_INPUT,
    REVIEW_PR_INPUT,
    REVIEW_REF_INPUT,
    TRIAGE_TOOL,
    finding_comment,
    review_inputs,
)
from engine.domain.forge import MODE_INPUT, ForgeMode, forge_mode
from engine.domain.ids import (
    AgentId,
    AgentInstanceId,
    AgentRunId,
    ApprovalId,
    ConversationId,
    MessageId,
    MilestoneId,
    ProjectId,
    RunId,
    SessionGrantId,
    StepId,
    TaskId,
    WorkflowId,
    WorkOrderId,
    WorkspaceId,
)
from engine.domain.state import RunOrigin, RunPhase, RunState
from engine.domain.states import STATE_INPUT, WorkState, start_state
from engine.domain.scoping import (
    TicketLayer,
    TicketApproval,
    TicketSourceKind,
    TicketSourceRef,
    PersistedScopingPlan,
    LoopQueueItem,
    resolve_scoping_plan,

    MilestoneScope,
    ScopingPlan,
    ScopingPolicy,
    Supersession,
    WorkOrder,
    WorkOrderSpec,
    WorkOrderStatus,
)
from engine.domain.tools import ToolParameter, ToolParameterType, ToolSpec
from engine.domain.workflow import StepOutput, StepSpec

__all__ = [
    "TicketLayer",
    "TicketApproval",
    "TicketSourceKind",
    "TicketSourceRef",
    "PersistedScopingPlan",
    "LoopQueueItem",
    "resolve_scoping_plan",

    "AgentId",
    "AgentInstance",
    "AgentInstanceId",
    "AgentProfile",
    "AgentRun",
    "AgentRunId",
    "AgentRunStatus",
    "ApprovalDecision",
    "ApprovalDecisionSource",
    "ApprovalId",
    "ApprovalKind",
    "ApprovalRecord",
    "ApprovalStatus",
    "Command",
    "Conversation",
    "ConversationId",
    "Event",
    "ForgeMode",
    "MODE_INPUT",
    "forge_mode",
    "finding_comment",
    "review_inputs",
    "REVIEW_BRANCH_INPUT",
    "REVIEW_PR_INPUT",
    "REVIEW_REF_INPUT",
    "TRIAGE_TOOL",
    "Message",
    "MessageId",
    "MilestoneId",
    "MilestoneScope",
    "Notify",
    "PersistRun",
    "ProvisionWorkspace",
    "ProjectId",
    "PublishChanges",
    "Role",
    "RunFailed",
    "RunId",
    "RunOrigin",
    "RunPhase",
    "RunState",
    "ScheduleTimer",
    "ScopingPlan",
    "ScopingPolicy",
    "SessionGrant",
    "SessionGrantId",
    "StartAgentRun",
    "StepCompleted",
    "StepId",
    "StepOutput",
    "StepSpec",
    "TaskId",
    "ToolCall",
    "ToolParameter",
    "ToolParameterType",
    "ToolSpec",
    "Supersession",
    "WorkflowId",
    "WorkOrder",
    "WorkOrderId",
    "WorkOrderSpec",
    "WorkOrderStatus",
    "WorkState",
    "STATE_INPUT",
    "start_state",
    "WorkspaceId",
]
