"""Generated by scripts/generate_cli_docs.py; edit graph_service parser sources."""


from inspect import getdoc


def graph_spec(_arguments: object = None) -> int:
    """Print the current graph specification as Markdown, without contacting a backend.

    A graph is a YAML definition or a Python LangGraph file. Register it with
    `engine graph add FILE`; run it with `engine graph execute GRAPH INSTRUCTION`.
    Names belong to projects, versions are immutable, and registering an unchanged
    definition is a no-op. `engine graph get GRAPH --pretty` prints stored source.

    ### YAML graph specification (openengine.dev/v1)

    ```yaml
    apiVersion: openengine.dev/v1
    kind: Graph
    name: implement-review
    inputs:
      instruction: {description: The change to make}
    implementation:
      implement:
        agent: claude
        prompt: "Implement ${instruction}"
    review:
      reviewer:
        agent: {not: implement}
        prompt: "Review ${outputs.implement}"
    loop:
      every: 6h
      instruction: Find and fix one flaky test.
    ```

    Supported YAML fields (from parser validation):

    | Declaration | Fields |
    | --- | --- |
    | graph | `apiVersion`, `description`, `flow`, `implementation`, `inputs`, `kind`, `loop`, `name`, `plan`, `repository`, `review` |
    | input | `choices`, `default`, `description`, `required` |
    | checkout | `base_ref`, `description`, `name`, `ref` |
    | human step | `description`, `human`, `name` |
    | human | `choose`, `prompt` |
    | ci step | `ci`, `description`, `name` |
    | agent step | `agent`, `description`, `facets`, `model`, `name`, `outputs`, `prompt`, `steering`, `tools` |
    | runner | `choices`, `not`, `same` |
    | output | `description`, `enum`, `lineage`, `required`, `type` |
    | flow | `from`, `route`, `to` |
    | route | `to`, `when` |
    | loop | `every`, `instruction` |

    Scalar field constraints:

    | Declaration | Field | Meaning | Constraints |
    | --- | --- | --- | --- |
    | loop | instruction | Default instruction for recurring runs; null or empty values are normalized to empty text. | default: `''`; type: str |
    | graph | apiVersion | Graph language version. | required; choices: `'openengine.dev/v1'` |
    | graph | kind | Definition kind. | default: `'Graph'`; choices: `'Graph'` |
    | graph | name | Project-scoped graph name. | required; type: str; pattern: `^[a-z0-9][a-z0-9._-]{0,62}$` |
    | input | required | Whether the value is required. | default: `False`; type: bool |
    | agent step | prompt | What the agent is asked to do. | required; type: str; nonblank |
    | agent step | model | Model tier, model name, or expression template. | default: `''`; type: str |
    | agent step | steering | Allow steering while the agent runs. | default: `None`; choices: `None`, `'always-open'` |
    | output | required | Whether the value is required. | default: `False`; type: bool |
    | output | type | Output value type. | default: `'string'`; choices: `'string'`, `'number'`, `'integer'`, `'boolean'`, `'list'`, `'object'`, `'findings'` |

    Unknown fields are rejected. Scalar constraints and defaults are listed above.

    `inputs` maps names to input declarations listed above. The
    instruction is built in; declaring `inputs.instruction` only describes it.
    Other inputs are supplied with `--input NAME=VALUE` when executing a graph.

    Steps are mappings in `plan`, `implementation` and `review`, executed in
    that order and in written order within each section. Step names are unique.
    At least one executable step is required. A checkout must come first; if
    omitted, a checkout named `workspace` is inserted. A checkout accepts
    `base_ref` and `ref: ${inputs.NAME}` (plus `name` and `description`).

    A step's keys determine its kind:

    - `agent` and `prompt`: an agent session. `agent` names a configured runner,
      uses `${inputs.NAME}`, or selects `{same: STEP}` or `{not: STEP}`.
      Runner inputs need a default or choices; `least-utilized`, `round-robin`
      are supported selection policies in those inputs.
    - `human`: a question, or `{prompt, choose}` for a person to select findings.
    - `ci: true`: wait for CI on the change.
    - None of these keys: the checkout.

    Steps accept `name` and `description`. Agent steps also accept `tools`,
    `outputs`, `model`, `steering` and `facets`. Tools must be
    registered repository tools. Outputs map names to declarations with `type`,
    `enum`, `required`, `description` and `lineage: required` for findings.
    Types are `string`, `number`, `integer`, `boolean`, `list`, `object`, `findings`. A model may be a tier, model name or template. Facets run in
    parallel, using a built-in facet or a custom `{id, name, focus}`; extra
    fields become `item`. Outputs of a parallel step form a list.

    `flow` overrides written-order edges. Use `a -> b`, `[a, b] -> c` for a join,
    or `{from: STEP, route: [{when: CONDITION, to: STEP}, {to: end}]}` for
    routing. Routes try branches in order and require an unconditional final
    branch. `start` and `end` mark entry and exit. Cycles must pass through a
    route; every step must be reachable and able to finish.

    Templates use `${...}`. Expression roots: `inputs`, `instruction`, `item`, `outputs`, `repository`, `visits`.
    Operators: `&&`, `||`, `!`, `-`, `+`, `*`, `/`, `%`, `==`, `!=`, `<`, `<=`, `>`, `>=`, `in`.
    Functions: `has(...)`, `json(...)`, `lower(...)`, `size(...)`.
    Literal words: `true`, `false`, `null`; text and numeric literals are supported.
    Attribute: `outputs.STEP.field`.
    Subscript: `outputs.STEP.items[0]`.
    List: `[1, 2]`.
    Express "not in" as `(!(item in inputs.items))`; Python's `not` keyword is rejected. Expressions cannot execute Python. Undeclared inputs and unavailable outputs are reported at registration.

    `loop` accepts `every`, `instruction`, defaults for `engine loop add`.
    See `engine loop spec` for cadence, limits and lifecycle.

    ### Python graph specification

    A Python file exports `workflow`, a `GraphWorkflow` or a tuple of them built
    with `graph_workflow` and the engine's LangGraph components. Its id supplies
    the default graph name. The backend loads and compiles it with its runtime;
    Python runs with daemon privileges and can be disabled by
    `[graphs] allow_python = false`. YAML and Python share the same registry,
    version history, checkpoints, approvals, steering and run feed.
    """
    print(getdoc(graph_spec))
    return 0


def loop_spec(_arguments: object = None) -> int:
    """Print the current loop specification as Markdown, without contacting a backend.

    A loop creates recurring runs of one pinned graph version. Create it with
    `engine loop add GRAPH`, where GRAPH is a name, `name@VERSION`, graph id or
    version id. Later registrations never change the pinned version.

    ### Defaults and creation

    A YAML graph may supply defaults:

    ```yaml
    loop:
      every: 6h
      instruction: Find and fix one flaky test.
    ```

    `loop` accepts `every`, `instruction`. `--every` and `--instruction`
    override them. Both an instruction and a cadence must be available; neither
    is invented. Cadences are integer seconds in YAML/API, or durations such as
    `90s`, `30m`, `6h` and `1d`, with a minimum of 60 seconds.
    Duration units (seconds per unit): `s = 1`, `m = 60`, `h = 3600`, `d = 86400`.

    `--name` defaults to the graph's name and must be unique within its project.
    `--project` scopes graph lookup, `--repo` selects the repository, and
    `--input NAME=VALUE` supplies graph inputs. `--backend` selects the daemon.
    The first run is due immediately unless `--no-run-now` delays it one interval.

    - `instruction`: Default instruction for recurring runs; null or empty values are normalized to empty text. default: `''`; type: str.

    ### Scheduling and limits

    Runs never overlap. Ticks missed while a run is active collapse into one;
    each tick is recorded before starting its run so duplicate ticks do nothing.
    Limits are cumulative over the loop's lifetime and survive restarts.

    - `--max-prs` limits new pull requests opened by runs, excluding updates to
      existing pull requests. Reaching it pauses the loop; the active run may
      finish.
    - `--max-spend` limits USD of reported agent usage, using session cost or
      token pricing when available. It excludes CI, hosting and unpriced
      subscription usage. If usage is unpriced, `spendEnforceable` is false.
      The active run reserves the remaining budget and is cancelled when the
      loop's spend reaches the cap.
    - A loop also pauses when a run fails because a runner needs to sign in.

    ### Inspection and lifecycle

    `engine loops list` lists loops. `engine loop get NAME_OR_ID` reports state,
    the pinned graph version, instruction, inputs, cadence, next run, active run,
    runs, pull requests, spend and limits. Use `--pretty` for readable output.

    `engine loop pause NAME_OR_ID --reason TEXT` stops new runs.
    `engine loop resume NAME_OR_ID` restarts scheduling; it is refused while a
    limit is still reached. Supply higher `--max-prs` or `--max-spend` limits
    when resuming. Pausing does not cancel an active run.
    """
    print(getdoc(loop_spec))
    return 0
