"""The edit-reload loop in a source checkout, as one command.

`engine-web` serves whatever `vite build` last wrote and reads its
configuration once, so a source edit is invisible until a build, a Ctrl-C and a
restart have gone past it -- and which of the three tiers an edit landed in is
not something the running process tells you.

This supervises the two watchers the repository already depends on rather than
adding a third: Vite in front of the browser, where a component edit is
hot-swapped into the open page, and Uvicorn's reloader in front of the
application, where a Python, `engine.toml` or workflow edit restarts the
process that read them. Both are children of this one: one Ctrl-C, one merged
log, and neither tier left running when the other stops.

`docs/dev-server.md` is the plan this implements, including what it does not
do: a restart still ends whatever agent runs are in flight.
"""

import argparse
import os
import signal
import socket
import subprocess
import sys
import threading
import time
from collections.abc import Callable, Mapping, Sequence
from contextlib import suppress
from dataclasses import dataclass
from pathlib import Path

from engine.apps.web.__main__ import read_configuration
from engine.apps.web.composition import Settings
from engine.runtime import (
    CONFIG_ENVIRONMENT_VARIABLE,
    EngineConfigError,
    WorkflowLoadError,
    describe_loaded_config,
)

#: `apps/web`, and the checkout it sits in.
WEB_ROOT = Path(__file__).resolve().parents[4]
REPO_ROOT = WEB_ROOT.parents[1]

#: What each reload child constructs. An import string rather than an
#: application object, because a fresh child process has to build its own.
APPLICATION = "engine.apps.web.__main__:build_app"

#: Where `vite.config.ts` sends the prefixes it proxies -- `/api`, and `/graph`
#: for the graph engine's own control surface. Told rather than assumed, because
#: the API takes a free port when its usual one is held by something else.
API_URL_ENVIRONMENT_VARIABLE = "ENGINE_API_URL"

#: What a restart is for: Python, and the TOML read once at startup. Workflow
#: definitions are Python, so `*.py` already covers them.
RELOAD_INCLUDES = ("*.py", "*.toml")

#: The server writes these itself, on every message. Watching the checkout
#: without excluding them means a chat turn restarts the server mid-turn.
RELOAD_EXCLUDED_PATTERNS = ("*.sqlite3*",)

#: Other people's files, all of which contain matches for the patterns above:
#: the virtualenv and `node_modules` are full of them, `dist` is regenerated by
#: the build, and `.git` churns on every command.
RELOAD_EXCLUDED_DIRECTORIES = (
    ".git",
    ".venv",
    ".pytest_cache",
    ".ruff_cache",
    "apps/web/dist",
    "apps/web/node_modules",
    "apps/web/playwright-report",
    "apps/web/test-results",
)

#: Changes no restart can pick up, and the command that can. Printed rather
#: than run: both are slow and both mutate the environment, and a tool doing
#: either unannounced in the middle of an edit is worse than a line of text.
DEPENDENCY_COMMANDS = {
    "pyproject.toml": "uv sync --all-packages",
    "uv.lock": "uv sync --all-packages",
    "package.json": "npm --prefix apps/web install",
    "package-lock.json": "npm --prefix apps/web install",
}

#: How often the dependency files are checked, and how long a child gets to
#: stop politely before it is killed.
DEPENDENCY_POLL_SECONDS = 2.0
SHUTDOWN_TIMEOUT_SECONDS = 10.0


# --- what the reloader watches ----------------------------------------------


@dataclass(frozen=True, slots=True)
class ReloadWatch:
    """The reloader's whole answer to "does this change need a restart?"."""

    directories: tuple[Path, ...]
    includes: tuple[str, ...]
    excludes: tuple[str, ...]


def reload_watch(
    *, config_path: Path | None = None, workspace_root: Path | None = None
) -> ReloadWatch:
    """What to watch for a checkout, and what to ignore inside it.

    The checkout as a whole, because the startup-time reads are spread across
    it -- `packages/` and `apps/`, `workflows/`, and `engine.toml` beside them
    -- and because a list of source directories is a list that goes stale. That
    makes the exclusions the substance of this: everything the tree contains
    that is written by something other than a person editing source.

    `workspace_root` is where agent worktrees are made. It defaults outside the
    checkout, and is excluded when it is not: an agent editing files under a
    watched root would restart the server underneath its own run.
    """
    directories = [REPO_ROOT]
    if config_path is not None and REPO_ROOT not in config_path.parents:
        directories.append(config_path.parent)

    candidates = [REPO_ROOT / name for name in RELOAD_EXCLUDED_DIRECTORIES]
    if workspace_root is not None and REPO_ROOT in workspace_root.parents:
        candidates.append(workspace_root)

    return ReloadWatch(
        directories=tuple(directories),
        includes=RELOAD_INCLUDES,
        # Absolute, because the reloader matches an exclusion against absolute
        # paths: a relative one is silently no exclusion at all. Existing, for
        # the other half of the same reason -- the reloader decides once, at
        # startup, whether an exclusion names a directory or a glob, and a path
        # that is neither yet would be read as a glob that matches nothing.
        excludes=(
            *(str(path) for path in candidates if path.is_dir()),
            *RELOAD_EXCLUDED_PATTERNS,
        ),
    )


# --- the two children -------------------------------------------------------


def api_command(*, host: str, port: int, watch: ReloadWatch) -> list[str]:
    """Uvicorn, reloading, around an application each child builds for itself."""
    command = [
        sys.executable,
        "-m",
        "uvicorn",
        APPLICATION,
        "--factory",
        "--host",
        host,
        "--port",
        str(port),
        "--reload",
    ]
    for directory in watch.directories:
        command += ["--reload-dir", str(directory)]
    for pattern in watch.includes:
        command += ["--reload-include", pattern]
    for pattern in watch.excludes:
        command += ["--reload-exclude", pattern]
    return command


def web_command(*, port: int | None = None) -> list[str]:
    """The Vite dev server, which owns the browser tier."""
    command = ["npm", "--prefix", str(WEB_ROOT), "run", "dev", "--", "--strictPort"]
    if port is not None:
        command += ["--port", str(port)]
    return command


def build_command() -> list[str]:
    """The production build, for `--build`."""
    return ["npm", "--prefix", str(WEB_ROOT), "run", "build"]


def child_environment(
    base: Mapping[str, str], *, config_path: Path | None = None, api_url: str | None = None
) -> dict[str, str]:
    """What each child is told about the half of the system it cannot see.

    A reload child parses no command line of ours, so the configuration
    selection reaches it through `ENGINE_CONFIG` -- the variable that already
    means exactly this, and that `--config` already outranks.
    """
    environment = dict(base)
    if config_path is not None:
        environment[CONFIG_ENVIRONMENT_VARIABLE] = str(config_path)
    if api_url is not None:
        environment[API_URL_ENVIRONMENT_VARIABLE] = api_url
    return environment


# --- dependency changes a restart cannot fix --------------------------------


def dependency_files() -> tuple[Path, ...]:
    """Every manifest and lockfile in the workspace, found the way uv finds them."""
    patterns = (
        "pyproject.toml",
        "uv.lock",
        "packages/*/pyproject.toml",
        "packages/adapters/*/*/pyproject.toml",
        "apps/*/pyproject.toml",
        "apps/web/package.json",
        "apps/web/package-lock.json",
    )
    return tuple(sorted({path for pattern in patterns for path in REPO_ROOT.glob(pattern)}))


def dependency_notice(path: Path) -> str | None:
    """What to say when a dependency file changes, or `None` for anything else."""
    command = DEPENDENCY_COMMANDS.get(path.name)
    if command is None:
        return None
    with suppress(ValueError):
        path = path.relative_to(REPO_ROOT)
    return (
        f"{path} changed; run `{command}` -- a restart alone does not pick that up"
    )


def watch_dependencies(stop: threading.Event, announce: Callable[[str], None]) -> None:
    """Poll the manifests, because nobody edits one by accident.

    Deliberately separate from the reloader: this reports, and the reloader
    restarts. A change here does both, and the restart on its own would leave
    somebody debugging a missing package.
    """
    seen = {path: _modified_at(path) for path in dependency_files()}
    while not stop.wait(DEPENDENCY_POLL_SECONDS):
        for path, previously in seen.items():
            current = _modified_at(path)
            if current == previously:
                continue
            seen[path] = current
            notice = dependency_notice(path)
            if notice is not None:
                announce(f"[dev] {notice}")


def _modified_at(path: Path) -> float | None:
    try:
        return path.stat().st_mtime
    except OSError:
        return None


# --- supervision ------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class Child:
    name: str
    process: "subprocess.Popen[str]"


def start(name: str, command: Sequence[str], environment: Mapping[str, str]) -> Child:
    """Run one tier in a session of its own.

    Its own session because `npm` starts Vite and Uvicorn starts its reload
    child: signalling the process we spawned would leave the process doing the
    work behind, still holding the port.
    """
    process = subprocess.Popen(
        list(command),
        cwd=REPO_ROOT,
        env=dict(environment),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        start_new_session=True,
    )
    return Child(name=name, process=process)


def relay(child: Child, announce: Callable[[str], None]) -> None:
    """One prefixed line at a time, so two tiers can share one terminal."""
    assert child.process.stdout is not None
    for line in child.process.stdout:
        announce(f"[{child.name}] {line.rstrip()}")


def stop(child: Child) -> None:
    """Interrupt the child's whole session, then insist."""
    if child.process.poll() is not None:
        return
    _signal(child, signal.SIGINT)
    if _ended_within(child, SHUTDOWN_TIMEOUT_SECONDS):
        return
    _signal(child, signal.SIGKILL)
    _ended_within(child, SHUTDOWN_TIMEOUT_SECONDS)


def _signal(child: Child, sent: signal.Signals) -> None:
    with suppress(ProcessLookupError, PermissionError):
        os.killpg(os.getpgid(child.process.pid), sent)


def _ended_within(child: Child, timeout: float) -> bool:
    """Whether the child stopped in time."""
    try:
        child.process.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        return False
    return True


def supervise(children: Sequence[Child], announce: Callable[[str], None]) -> int:
    """Run until one tier stops or the terminal interrupts, then stop the rest.

    Ctrl-C is taken as a flag rather than as an exception for the length of
    this: a second one arrives while the first one's shutdown is still walking
    the children, and a `KeyboardInterrupt` raised there -- anywhere there --
    would leave whichever tier it had not reached yet running and holding its
    port.
    """
    interrupted = threading.Event()
    handled_signals = (signal.SIGINT, signal.SIGTERM)
    previously = {
        sent: signal.signal(sent, lambda _number, _frame: interrupted.set())
        for sent in handled_signals
    }
    for child in children:
        threading.Thread(target=relay, args=(child, announce), daemon=True).start()
    try:
        while not interrupted.is_set():
            for child in children:
                code = child.process.poll()
                if code is not None:
                    announce(f"[dev] {child.name} exited with {code}; stopping the rest")
                    return code
            time.sleep(0.2)
        return 0
    finally:
        for child in children:
            stop(child)
        for sent, handler in previously.items():
            signal.signal(sent, handler)


# --- ports ------------------------------------------------------------------


def chosen_port(host: str, preferred: int) -> int:
    """`preferred` if it is free, otherwise any free port.

    A dev server that refuses to start because the last one has not let go of
    8000 yet is a dev server people stop using; the browser is told which port
    it got either way.
    """
    if _is_free(host, preferred):
        return preferred
    with socket.socket() as taken:
        taken.bind((host, 0))
        return int(taken.getsockname()[1])


def _is_free(host: str, port: int) -> bool:
    with socket.socket() as probe:
        try:
            probe.bind((host, port))
        except OSError:
            return False
    return True


# --- entrypoint -------------------------------------------------------------


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="engine-dev",
        description="Run the OpenEngine web interface with both tiers reloading.",
    )
    parser.add_argument("--config", help="read Engine settings from this TOML file")
    parser.add_argument(
        "--port",
        type=int,
        help="serve the API here (default: 8000, or a free port if that is taken)",
    )
    parser.add_argument(
        "--web-port", type=int, help="serve the interface here (default: Vite's own)"
    )
    parser.add_argument(
        "--no-web",
        action="store_true",
        help="run the reloading API alone, for work that never reaches the browser",
    )
    parser.add_argument(
        "--build",
        action="store_true",
        help="build the client once and serve it from the API, as `engine-web` does",
    )
    args = parser.parse_args(argv)

    try:
        loaded, _ = read_configuration(args.config)
    except (EngineConfigError, WorkflowLoadError) as error:
        # Reported here rather than left to the reload child: a child that
        # cannot import the application exits, and the reloader would then sit
        # there waiting for a file change to try again.
        print(f"configuration error: {error}", file=sys.stderr)
        return 2

    settings = Settings(engine_config=loaded.config, config_path=loaded.path)
    port = args.port if args.port is not None else chosen_port(settings.host, settings.port)
    api_url = f"http://{settings.host}:{port}"

    def announce(line: str) -> None:
        print(line, flush=True)

    if args.build:
        announce("[dev] building the client")
        built = subprocess.run(build_command(), cwd=REPO_ROOT)
        if built.returncode != 0:
            return built.returncode

    environment = child_environment(
        os.environ, config_path=loaded.path, api_url=api_url
    )
    watch = reload_watch(
        config_path=loaded.path, workspace_root=Path(settings.workspace_root)
    )
    children = [
        start(
            "api",
            api_command(host=settings.host, port=port, watch=watch),
            environment,
        )
    ]
    serves_the_browser = not (args.no_web or args.build)
    if serves_the_browser:
        children.append(
            start("web", web_command(port=args.web_port), environment)
        )

    announce(describe_loaded_config(loaded))
    announce(f"[dev] api {api_url}")
    if serves_the_browser:
        announce("[dev] the interface is the address Vite prints below")
    else:
        announce(f"[dev] the interface is served from {api_url} by the API")

    stopping = threading.Event()
    threading.Thread(
        target=watch_dependencies, args=(stopping, announce), daemon=True
    ).start()
    try:
        return supervise(children, announce)
    finally:
        stopping.set()


if __name__ == "__main__":
    raise SystemExit(main())
