"""Generate bundled CLI specs and the site reference from parser-owned definitions.

Uses only the standard library: python3 scripts/generate_cli_docs.py
"""

from inspect import getdoc
from pathlib import Path
from runpy import run_path

ROOT = Path(__file__).resolve().parents[1]
SERVICE = ROOT / "cli/service/src/engine/graph_service"
CLIENT = ROOT / "cli/client/src/engine/cli/specs.py"


def specifications() -> dict[str, str]:
    schema = run_path(str(SERVICE / "schema.py"))
    expressions = run_path(str(SERVICE / "expressions.py"))
    prose = run_path(str(SERVICE / "specification.py"))

    def code(values) -> str:
        return ", ".join(f"`{value}`" for value in values)

    fields = schema["FIELDS"]
    rules = schema["FIELD_RULES"]
    field_details = "\n\nScalar field constraints:\n\n| Declaration | Field | Meaning | Constraints |\n| --- | --- | --- | --- |\n"
    field_details += "\n".join(
        f"| {declaration} | {name} | {field.description} | {field.constraints()} |"
        for declaration, fields in rules.items() for name, field in fields.items()
    )
    replacements = {
        "API_VERSION": schema["API_VERSION"],
        "KIND": schema["KIND"],
        "GRAPH_FIELDS": "Supported YAML fields (from parser validation):\n\n"
        + "| Declaration | Fields |\n| --- | --- |\n"
        + "\n".join(f"| {name} | {code(sorted(values))} |" for name, values in fields.items()) + field_details,
        "LOOP_DETAILS": "\n".join(
            f"- `{name}`: {field.description} {field.constraints()}."
            for name, field in rules["loop"].items()
        ),
        "LOOP_FIELDS": code(sorted(fields["loop"])),
        "OUTPUT_TYPES": code(schema["OUTPUT_TYPES"]),
        "RUNNER_POLICIES": code(schema["RUNNER_POLICIES"]),
        "MIN_INTERVAL_SECONDS": str(schema["MIN_INTERVAL_SECONDS"]),
        "UNITS": code(f"{unit} = {seconds}" for unit, seconds in schema["_UNITS"].items()),
        "EXPRESSIONS": expressions["specification"](),
    }
    result = {}
    for command in ("graph", "loop"):
        text = getdoc(prose[f"{command}_spec"])
        for key, value in replacements.items():
            text = text.replace(f"@{key}@", value)
        result[command] = text
    return result


def render_cli() -> str:
    sections = ['"""Generated by scripts/generate_cli_docs.py; edit graph_service parser sources."""',
                "from inspect import getdoc"]
    for command, text in specifications().items():
        sections.append(
            f"def {command}_spec(_arguments: object = None) -> int:\n"
            + '    """' + text.replace("\n", "\n    ") + '\n    """\n'
            + f"    print(getdoc({command}_spec))\n    return 0"
        )
    return "\n".join(line.rstrip() for line in "\n\n\n".join(sections).splitlines()) + "\n"


def render() -> str:
    sections = [
        "# Graph and loop specifications",
        "> Generated by `scripts/generate_cli_docs.py` from `graph_service` parser sources.",
    ]
    for command, text in specifications().items():
        sections.append(f"## `engine {command} spec`\n\n{text}")
    return "\n\n".join(sections) + "\n"


if __name__ == "__main__":
    CLIENT.write_text(render_cli(), encoding="utf-8")
    (ROOT / "site/docs/cli-specs.md").write_text(render(), encoding="utf-8")
