"""Generate bundled CLI specs and the site references from parser-owned definitions.

The specifications use only the standard library: python3 scripts/generate_cli_docs.py
The command reference needs the `engine` parser, so run it in the workspace
environment (uv run python scripts/generate_cli_docs.py). Without it, the
committed reference is kept; tests reject a stale one.
"""

import argparse
from inspect import getdoc
from pathlib import Path
from runpy import run_path

ROOT = Path(__file__).resolve().parents[1]
SERVICE = ROOT / "cli/service/src/engine/graph_service"
CLIENT = ROOT / "cli/client/src/engine/cli/specs.py"


def specifications() -> dict[str, str]:
    schema = run_path(str(SERVICE / "schema.py"))
    expressions = run_path(str(SERVICE / "expressions.py"))
    prose = run_path(str(SERVICE / "specification.py"))

    def code(values) -> str:
        return ", ".join(f"`{value}`" for value in values)

    fields = schema["FIELDS"]
    rules = schema["FIELD_RULES"]
    field_details = "\n\nScalar field constraints:\n\n| Declaration | Field | Meaning | Constraints |\n| --- | --- | --- | --- |\n"
    field_details += "\n".join(
        f"| {declaration} | {name} | {field.description} | {field.constraints()} |"
        for declaration, fields in rules.items() for name, field in fields.items()
    )
    replacements = {
        "API_VERSION": schema["API_VERSION"],
        "KIND": schema["KIND"],
        "GRAPH_FIELDS": "Supported YAML fields (from parser validation):\n\n"
        + "| Declaration | Fields |\n| --- | --- |\n"
        + "\n".join(f"| {name} | {code(sorted(values))} |" for name, values in fields.items()) + field_details,
        "LOOP_DETAILS": "\n".join(
            f"- `{name}`: {field.description} {field.constraints()}."
            for name, field in rules["loop"].items()
        ),
        "LOOP_FIELDS": code(sorted(fields["loop"])),
        "OUTPUT_TYPES": code(schema["OUTPUT_TYPES"]),
        "RUNNER_POLICIES": code(schema["RUNNER_POLICIES"]),
        "MIN_INTERVAL_SECONDS": str(schema["MIN_INTERVAL_SECONDS"]),
        "UNITS": code(f"{unit} = {seconds}" for unit, seconds in schema["_UNITS"].items()),
        "EXPRESSIONS": expressions["specification"](),
    }
    result = {}
    for command in ("graph", "loop"):
        text = getdoc(prose[f"{command}_spec"])
        for key, value in replacements.items():
            text = text.replace(f"@{key}@", value)
        result[command] = text
    return result


def render_cli() -> str:
    sections = ['"""Generated by scripts/generate_cli_docs.py; edit graph_service parser sources."""',
                "from inspect import getdoc"]
    for command, text in specifications().items():
        sections.append(
            f"def {command}_spec(_arguments: object = None) -> int:\n"
            + '    """' + text.replace("\n", "\n    ") + '\n    """\n'
            + f"    print(getdoc({command}_spec))\n    return 0"
        )
    return "\n".join(line.rstrip() for line in "\n\n\n".join(sections).splitlines()) + "\n"


def render() -> str:
    sections = [
        "# Graph and loop specifications",
        "> Generated by `scripts/generate_cli_docs.py` from `graph_service` parser sources.",
    ]
    for command, text in specifications().items():
        sections.append(f"## `engine {command} spec`\n\n{text}")
    return "\n\n".join(sections) + "\n"


def _subcommands(parser: argparse.ArgumentParser) -> list[tuple[str, str, argparse.ArgumentParser]]:
    """Advertised subcommands: those given help, so hidden ones stay out."""
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return [(choice.dest, choice.help, action.choices[choice.dest]) for choice in action._choices_actions]
    return []


def _argument_rows(parser: argparse.ArgumentParser) -> list[str]:
    rows = []
    for action in parser._actions:
        if isinstance(action, (argparse._HelpAction, argparse._SubParsersAction)) or action.help == argparse.SUPPRESS:
            continue
        name = ", ".join(action.option_strings) or action.metavar or action.dest
        if action.option_strings and action.nargs != 0:
            name += f" {action.metavar or action.dest.upper()}"
        meaning = (action.help or "").replace("|", "\\|")
        if action.choices and not action.option_strings:
            meaning = (meaning + "; " if meaning else "") + "one of " + ", ".join(f"`{c}`" for c in action.choices)
        rows.append(f"| `{name}` | {meaning} |")
    return rows


def _command_sections(prefix: str, parser: argparse.ArgumentParser, depth: int) -> list[str]:
    sections = []
    for name, help_text, child in _subcommands(parser):
        command = f"{prefix} {name}"
        child.formatter_class = lambda prog: argparse.HelpFormatter(prog, width=100)
        # Drop "usage: " and the indent argparse aligns continuation lines to it with.
        usage = "\n".join(line[len("usage: "):] for line in child.format_usage().rstrip().splitlines())
        help_text = help_text or ""
        body = [f"{'#' * depth} `{command}`", help_text[:1].upper() + help_text[1:] + "."]
        if name == "spec":
            body.append("Prints the [specification](cli-specs.md) as Markdown, without contacting a backend.")
        elif child.description:
            body.append(child.description)
        body.append(f"```text\n{usage}\n```")
        if rows := _argument_rows(child):
            body.append("| Argument | Meaning |\n| --- | --- |\n" + "\n".join(rows))
        sections.append("\n\n".join(body))
        sections.extend(_command_sections(command, child, depth + 1))
    return sections


def render_reference(parser: argparse.ArgumentParser | None = None) -> str:
    """The `engine` command reference, from the parser the command itself uses."""
    if parser is None:
        from engine.apps.cli.__main__ import parser as engine_parser

        parser = engine_parser()
    sections = [
        "---\ntitle: CLI reference\ndescription: Every engine command, its arguments and options.\n---",
        "> Generated by `scripts/generate_cli_docs.py` from the `engine` argument parser.",
        "Backend commands talk to the selected backend (`--backend`, else `ENGINE_BACKEND`, else the one "
        "`engine backend use` chose) and print JSON unless `--pretty` is given. Exit status is 0 on success, "
        "1 on a refusal or failed run, and 2 on a usage mistake. "
        "See [Graphs](graphs.md), [Loops](loops.md) and the [graph and loop specifications](cli-specs.md).",
        *_command_sections("engine", parser, 2),
    ]
    return "\n\n".join(sections) + "\n"


if __name__ == "__main__":
    CLIENT.write_text(render_cli(), encoding="utf-8")
    (ROOT / "site/docs/cli-specs.md").write_text(render(), encoding="utf-8")
    try:
        reference = render_reference()
    except ImportError as error:
        print(f"keeping site/docs/cli-reference.md: the engine parser is unavailable ({error})")
    else:
        (ROOT / "site/docs/cli-reference.md").write_text(reference, encoding="utf-8")
