"""Generate the spec command reference from the CLI's command docstrings.

Run with Python's standard library only, including during the site build:
    python3 scripts/generate_cli_docs.py
"""

from inspect import getdoc
from pathlib import Path
from runpy import run_path

ROOT = Path(__file__).resolve().parents[1]


def render() -> str:
    commands = run_path(str(ROOT / "cli/client/src/engine/cli/specs.py"))
    sections = [
        "# Graph and loop specifications",
        "> Generated by `scripts/generate_cli_docs.py`; edit `engine.cli.specs` instead.",
    ]
    for command in ("graph", "loop"):
        sections.append(f"## `engine {command} spec`\n\n{getdoc(commands[f'{command}_spec'])}")
    return "\n\n".join(sections) + "\n"


if __name__ == "__main__":
    (ROOT / "site/docs/cli-specs.md").write_text(render(), encoding="utf-8")
